import logging
import discord
import asyncio
from utils.sqlite_db import SQLiteDB

logger = logging.getLogger(__name__)

def saveRecentConversationSync(llm_response: str, message: discord.Message, character: str, user_input: str) -> None:
    """
    Synchronously saves the recent conversation to the database.

    Args:
        llm_response (str): The response generated by the LLM.
        message (discord.Message): The Discord message object.
        character (str): The roleplay character that the bot will respond as.
        user_input (str): The user's input message without the bot mention.

    Returns:
        None
    """
    if not user_input or user_input.strip() == "":
        logger.warning("User input is empty. Cannot save to user memory database.")
        return
    if not llm_response or llm_response.strip() == "":
        logger.warning("LLM response is empty. Cannot save to user memory database.")
        return
    if not message or not isinstance(message, discord.Message):
        logger.warning("Invalid message object. Cannot save to user memory database.")
        return
    if not character or character.strip() == "":
        logger.warning("Character is empty. Cannot save to user memory database.")
        return

    # Initialize the SQLite database connection
    sqlite_db: SQLiteDB = SQLiteDB()

    # Save the recent conversation to the database
    sqlite_db.append_message(
        str(message.id),
        character,
        str(message.author.id),
        message.author.name,
        user_input,
        llm_response,
        int(message.created_at.timestamp())
    )

async def saveRecentConversation(llm_response: str, message: discord.Message, character: str, user_input: str) -> bool:
    """
    Asynchronous wrapper for saving the recent conversation to the database.

    Args:
        llm_response (str): The response generated by the LLM.
        message (discord.Message): The Discord message object.
        character (str): The roleplay character that the bot will respond as.
        user_input (str): The user's input message without the bot mention.

    Returns:
        bool: True if the conversation was saved successfully, False otherwise.
    """
    logger.info("Saving recent conversation to database...")

    try:
        await asyncio.to_thread(saveRecentConversationSync, llm_response, message, character, user_input)
        logger.info("Recent conversation saved to database.")
        return True
    except Exception as e:
        logger.error(f"Error occurred while trying to save recent conversation: {e}")
        return False
    
def getRecentConversationSync(character: str, user_id: str, limit: int = 10) -> list[dict]:
    """
    Retrieves recent conversations for a specific character and user from the database.

    Args:
        character (str): The roleplay character to fetch messages for.
        user_id (str): The Discord ID of the user to fetch messages for.
        limit (int): The maximum number of messages to retrieve.

    Returns:
        list[dict]: A list of dictionaries containing recent conversation data.
    """
    if not character or character.strip() == "":
        logger.warning("Character is empty. Cannot retrieve recent conversations.")
        return []
    if not user_id or user_id.strip() == "":
        logger.warning("User ID is empty. Cannot retrieve recent conversations.")
        return []

    sqlite_db: SQLiteDB = SQLiteDB()
    rows = sqlite_db.get_recent_messages(character, user_id, limit)
        
    # Convert rows to a list of dictionaries
    recent_conversations = [
        {
            "message_id": row["message_id"],
            "character": row["character"],
            "user_id": row["user_id"],
            "username": row["username"],
            "user_input": row["user_input"],
            "llm_response": row["llm_response"],
            "timestamp": row["timestamp"]
        }
        for row in rows
    ]
        
    return recent_conversations

async def getRecentConversation(character: str, user_id: str, limit: int = 10) -> list[dict] | None:
    """
    Asynchronous wrapper for retrieving recent conversations for a specific character and user from the database.

    Args:
        character (str): The roleplay character to fetch messages for.
        user_id (str): The Discord ID of the user to fetch messages for.
        limit (int): The maximum number of messages to retrieve.

    Returns:
        list[dict] | None: A list of dictionaries containing recent conversation data, or None if an error occurs.
    """
    logger.info("Retrieving recent conversations from database...")

    try:
        recent_conversations = await asyncio.to_thread(getRecentConversationSync, character, user_id, limit)
        logger.info("Recent conversations retrieved from database.")
        return recent_conversations
    except Exception as e:
        logger.error(f"Error occurred while trying to retrieve recent conversations: {e}")
        return None