import asyncio
import json
import logging
import discord

from utils.chroma import ChromaDatabase

logger = logging.getLogger(__name__)

def saveToUserMemorySync(llm_response: str, message: discord.Message, character: str, user_input: str) -> None:
    """
    Synchronously saves the user input and LLM response to the user memory database.

    Args:
        llm_response (str): The response generated by the LLM.
        message (discord.Message): The Discord message object.
        character (str): The roleplay character that the bot will respond as.
        user_input (str): The user's input message without the bot mention.

    Returns:
        None
    """
    if not user_input or user_input.strip() == "":
        logger.warning("User input is empty. Cannot save to user memory database.")
        return
    if not llm_response or llm_response.strip() == "":
        logger.warning("LLM response is empty. Cannot save to user memory database.")
        return
    if not message or not isinstance(message, discord.Message):
        logger.warning("Invalid message object. Cannot save to user memory database.")
        return
    if not character or character.strip() == "":
        logger.warning("Character is empty. Cannot save to user memory database.")
        return

    # Initialize the user memory database    
    user_memory_database: ChromaDatabase = ChromaDatabase("./chroma_db", collection_names="user_memory")
    
    doc_id = str(message.id)

    existing_ids: list[str] = user_memory_database.collection.get(ids=[doc_id])["ids"]
    if doc_id in existing_ids:
        logger.error("Duplicate entry detected in user memory database. Skipping save.")
        return
    
    chunk = {
        "conversation": f"User ({message.author.name.capitalize()}): {user_input} | {character.capitalize()}: {llm_response}",
        "username": message.author.name,
        "character": character,
    }

    # Chroma expects documents to be strings — store JSON string
    chunk_str = json.dumps(chunk, ensure_ascii=False)

    # Metadata for the user memory entry
    metadata: dict = {
        "user_id": str(message.author.id),
        "username": message.author.name,
        "character": character,
        "date_added": message.created_at.strftime("%Y-%m-%d %H:%M:%S"),
        # "date_raw": int(message.created_at.timestamp()),
        # "source_channel": ... # Optional: Include source of the channel on Discord where the conversation took place.
    }

    # Add the user memory entry into the collection (or database)
    user_memory_database.collection.add(
        documents=[chunk_str],
        ids=[doc_id],
        metadatas=[metadata],
    )

async def saveToUserMemory(llm_response: str, message: discord.Message, character: str, user_input: str) -> bool:
    """
    Asynchronous wrapper for saving the user input and LLM response to the user memory database.

    Args:
        llm_response (str): The response generated by the LLM.
        message (discord.Message): The Discord message object.
        character (str): The roleplay character that the bot will respond as.
        user_input (str): The user's input message without the bot mention.

    Returns:
        None
    """
    logger.info("Saving to user memory database...")

    try:
        await asyncio.to_thread(saveToUserMemorySync, llm_response, message, character, user_input)
        logger.info("Data successfully saved to user memory database.")
        return True
    except Exception as e:
        logger.error(f"Error occurred while trying to save to user memory database: {e}")
        return False