import asyncio
from datetime import datetime
import hashlib
import logging
import json

from utils.chroma import ChromaDatabase

logger = logging.getLogger(__name__)

def saveToUserMemorySync(user_input: str, llm_response: str, username: str, character: str) -> None:
    """
    Synchronously saves the user input and LLM response to the user memory database.

    Args:
        user_input (str): The input message from the user.
        llm_response (str): The response generated by the LLM.
        username (str): The name of the user who sent the message.
        character (str): The roleplay character that the bot will respond as.    

    Returns:
        None
    """
    if not user_input or user_input.strip() == "":
        logger.warning("User input is empty. Cannot save to user memory database.")
        return
    if not llm_response or llm_response.strip() == "":
        logger.warning("LLM response is empty. Cannot save to user memory database.")
        return
    if not username or username.strip() == "":
        logger.warning("Username is empty. Cannot save to user memory database.")
        return
    if not character or character.strip() == "":
        logger.warning("Character is empty. Cannot save to user memory database.")
        return

    # Initialize the user memory database    
    user_memory_database: ChromaDatabase = ChromaDatabase("./chroma_db", collection_names="user_memory")
    
    doc_id = hashlib.md5(f"{username}_{user_input}_{str(datetime.now())}".encode("utf-8")).hexdigest()

    existing_ids: list[str] = user_memory_database.collection.get(ids=[doc_id])["ids"]
    if doc_id in existing_ids:
        logger.error("Duplicate entry detected in user memory database. Skipping save.")
        return
    
    chunk = {
        "conversation": f"User ({username.capitalize()}): {user_input} | {character.capitalize()}: {llm_response}",
        "username": username,
        "character": character,
    }

    # Chroma expects documents to be strings — store JSON string
    chunk_str = json.dumps(chunk, ensure_ascii=False)

    # Metadata for the user memory entry
    metadata: dict = {
        "username": username,
        "character": character,
        "date_added": str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        # "source_channel": ... # Optional: Include source of the channel on Discord where the conversation took place.
    }

    # Add the user memory entry into the collection (or database)
    user_memory_database.collection.add(
        documents=[chunk_str],
        ids=[doc_id],
        metadatas=[metadata],
    )

async def saveToUserMemory(user_input: str, llm_response: str, username: str, character: str) -> None:
    """
    Asynchronous wrapper for saving the user input and LLM response to the user memory database.

    Args:
        user_input (str): The input message from the user.
        llm_response (str): The response generated by the LLM.
        username (str): The name of the user who sent the message.
        character (str): The roleplay character that the bot will respond as.    

    Returns:
        None
    """
    logger.info("Saving to user memory database...")

    # Offload the synchronous save operation to a separate thread to avoid blocking the main event loop
    await asyncio.to_thread(saveToUserMemorySync, user_input, llm_response, username, character)
    
    logger.info("Data successfully saved to user memory database.")